apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
spec:
  limits:
  - default:
      cpu: "1500m"
      memory: "2500Mi"
    defaultRequest:
      cpu: "300m"
      memory: "300Mi"
    type: Container