kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: astm-developer-readonly-binding
subjects:
- kind: User
  name: kube-sudo-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: astm-developer-readonly
  apiGroup: rbac.authorization.k8s.io