kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: astm-readonly-podsandlogs-rolebinding
  namespace: default
subjects:
- kind: User
  name: kube-sudo-user
roleRef:
  kind: ClusterRole
  name: astm-readonly-podsandlogs
  apiGroup: rbac.authorization.k8s.io